# Generated by Django 2.0.5 on 2018-05-18 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='description',
            new_name='ticket_description',
        ),
    ]
