# Generated by Django 2.0.5 on 2018-05-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0002_auto_20180518_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_user_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
