# Generated by Django 2.0.5 on 2018-05-24 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sac', '0003_ticket_ticket_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='ticket_user_id',
        ),
    ]
